### ISSUE TITLE
API update, new functions and callbacks

### ISSUE THREAD

**Issue by filloax** [Yusyuriv/Afterbirth-API-for-ZeroBrane#2]

**Comment by Yusyuriv** [comment]
I haven't looked at the generated documentation for a while, and when I looked at it today, some files were missing (for example, `class_item_config_1_1_card.html`). Is there a version of documentation somewhere with those files?

**Comment by filloax** [comment]
I think the modding of Isaac has it, if not it should be there
I got a 404 error too, but it worked when opening it from the class index

**Comment by Yusyuriv** [comment]
Made an update. More information [here](https://github.com/Yusyuriv/Afterbirth-API-for-ZeroBrane/releases/tag/v1.7.0-beta).
